import { useEffect, useMemo, useState } from 'react'
import { ActionIcon, Alert, Badge, Box, Button, Card, FileButton, Group, Image, Modal, NumberInput, Paper, Select, SimpleGrid, Stack, Switch, Text, TextInput, Textarea, Title } from '@mantine/core'
import { Camera, ChevronLeft, ChevronRight, ImagePlus, PackagePlus, Plus, Trash2, X } from 'lucide-react'
import { acceptanceApi, absoluteMediaUrl, type AudienceSegment, type ProductView, type VariantSeed } from '../../acceptanceApi'
import type { InventoryType } from '../../types'
import './acceptance-v3.css'

type DraftVariant = VariantSeed & { key: string; size: string; colour: string }
type Draft = { name: string; sku: string; inventory_type: InventoryType; category: string; fabric: string; color: string; selling_price: string; cost_price: string; quantity: string; audience: AudienceSegment; collection: string; season: string; description: string }
const blank: Draft = { name: '', sku: '', inventory_type: 'UNIQUE', category: '', fabric: '', color: '', selling_price: '', cost_price: '', quantity: '1', audience: 'WOMEN', collection: '', season: '', description: '' }
const variant = (): DraftVariant => ({ key: crypto.randomUUID(), name: '', sku: '', option_values: {}, selling_price: '', cost_price: '', quantity: '0', size: '', colour: '' })
const money = (value: string | number) => `₹${Number(value).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`

export function CatalogWorkspaceV4() {
  const [products, setProducts] = useState<ProductView[]>([])
  const [query, setQuery] = useState('')
  const [category, setCategory] = useState('ALL')
  const [opened, setOpened] = useState(false)
  const [step, setStep] = useState(0)
  const [draft, setDraft] = useState<Draft>(blank)
  const [hasVariants, setHasVariants] = useState(false)
  const [variants, setVariants] = useState<DraftVariant[]>([variant()])
  const [files, setFiles] = useState<File[]>([])
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')

  const load = () => void acceptanceApi.products().then(setProducts).catch((e) => setError(e instanceof Error ? e.message : 'Unable to load products.'))
  useEffect(load, [])
  const categories = useMemo(() => ['ALL', ...Array.from(new Set(products.map((p) => p.category))).sort()], [products])
  const filtered = useMemo(() => products.filter((p) => {
    const haystack = `${p.name} ${p.sku ?? ''} ${p.category} ${p.fabric ?? ''} ${p.color ?? ''} ${p.collection ?? ''} ${p.variants.map((v) => `${v.name} ${v.sku ?? ''} ${Object.values(v.option_values).join(' ')}`).join(' ')}`.toLowerCase()
    return (!query.trim() || haystack.includes(query.toLowerCase())) && (category === 'ALL' || p.category === category)
  }), [products, query, category])

  function reset() { setOpened(false); setStep(0); setDraft(blank); setHasVariants(false); setVariants([variant()]); setFiles([]); setError('') }
  function patchVariant(key: string, patch: Partial<DraftVariant>) { setVariants((rows) => rows.map((row) => row.key === key ? { ...row, ...patch } : row)) }
  const basicsOk = Boolean(draft.name.trim() && draft.category.trim() && draft.selling_price !== '')
  const variantsOk = !hasVariants || (variants.length > 0 && variants.every((v) => v.name.trim() && Number(v.quantity) >= 0))

  async function save() {
    if (!basicsOk || !variantsOk) return
    setSaving(true); setError('')
    try {
      const created = await acceptanceApi.createProduct({ name: draft.name, sku: draft.sku || undefined, inventory_type: draft.inventory_type, category: draft.category, fabric: draft.fabric || undefined, color: draft.color || undefined, selling_price: draft.selling_price, cost_price: draft.cost_price || undefined, quantity: hasVariants ? '0' : draft.quantity, audience: draft.audience, collection: draft.collection || undefined, season: draft.season || undefined, description: draft.description || undefined, variants: hasVariants ? variants.map((v) => ({ name: v.name, sku: v.sku || undefined, option_values: { ...(v.size ? { size: v.size } : {}), ...(v.colour ? { colour: v.colour } : {}) }, selling_price: v.selling_price || undefined, cost_price: v.cost_price || undefined, quantity: v.quantity })) : [] })
      const uploaded = []
      for (const file of files) uploaded.push(await acceptanceApi.uploadProductImage(created.id, file))
      if (uploaded[0]) await acceptanceApi.markPrimaryMedia(created.id, uploaded[0].id)
      reset(); load()
    } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create product.') } finally { setSaving(false) }
  }

  return <Stack gap="lg">
    <Group justify="space-between" align="flex-end" className="v3-page-heading"><Box><Text size="sm" c="dimmed">Operations</Text><Title order={1}>Products</Title><Text c="dimmed">Merchandise visually; variants, stock and optional SKUs stay underneath.</Text></Box><Button color="grape" leftSection={<PackagePlus size={17}/>} onClick={() => setOpened(true)}>Add product</Button></Group>
    {error && <Alert color="red">{error}</Alert>}
    <TextInput size="md" placeholder="Search product, SKU, fabric, colour, collection or variant..." value={query} onChange={(e) => setQuery(e.currentTarget.value)}/>
    <Group gap="xs" className="v3-filter-scroll">{categories.map((c) => <Button key={c} size="xs" radius="xl" color="grape" variant={category === c ? 'filled' : 'light'} onClick={() => setCategory(c)}>{c === 'ALL' ? 'All' : c}</Button>)}</Group>
    <Box className="v3-merch-grid">{filtered.map((p) => { const src = absoluteMediaUrl(p.primary_media_url); return <Card key={p.id} withBorder padding={0} radius="lg" className="v3-merch-card"><Box className="v3-merch-image-wrap">{src ? <Image src={src} alt={p.name} h="100%" fit="cover"/> : <Box className="v3-merch-placeholder"><Camera size={42}/><Text size="sm" c="dimmed">No product image</Text></Box>}<Badge className="v3-stock-badge" color={p.availability === 'AVAILABLE' ? 'teal' : p.availability === 'HELD' ? 'orange' : 'gray'}>{p.availability.replaceAll('_',' ')}</Badge></Box><Stack p="md" gap="xs"><Group justify="space-between" align="flex-start" wrap="nowrap"><Box><Text fw={900}>{p.name}</Text><Text size="sm" c="dimmed">{[p.fabric,p.color].filter(Boolean).join(' · ') || p.category}</Text></Box><Text fw={900}>{money(p.selling_price)}</Text></Group><Group justify="space-between"><Text size="xs" c="dimmed">{p.audience ?? 'UNSPECIFIED'} · {p.inventory_type}</Text><Text size="sm" fw={700}>{p.variants.length ? `${p.variants.length} variants` : p.inventory_type === 'YARDAGE' ? `${Number(p.quantity_available)} m` : `${Number(p.quantity_available)} available`}</Text></Group>{p.variants.length > 0 && <Group gap={6}>{p.variants.slice(0,4).map((v) => <Badge key={v.id} color="grape" variant="light">{v.name} · {Number(v.quantity_available)}</Badge>)}</Group>}</Stack></Card> })}</Box>

    <Modal opened={opened} onClose={reset} title="Add product" size="xl" centered>
      <Stack gap="lg"><Group gap="xs" className="v3-stepper">{['Product','Images','Variants & stock','Review'].map((label,index) => <button type="button" key={label} className={index === step ? 'active' : index < step ? 'done' : ''} onClick={() => index < step && setStep(index)}><span>{index+1}</span>{label}</button>)}</Group>
      {step === 0 && <SimpleGrid cols={{ base: 1, sm: 2 }}><TextInput label="Product name" required value={draft.name} onChange={(e) => setDraft({...draft,name:e.currentTarget.value})}/><TextInput label="SKU" description="Optional" value={draft.sku} onChange={(e) => setDraft({...draft,sku:e.currentTarget.value})}/><Select label="Inventory type" value={draft.inventory_type} data={[{value:'UNIQUE',label:'Unique piece'},{value:'STOCKED',label:'Stocked item'},{value:'YARDAGE',label:'Fabric / yardage'}]} onChange={(value) => { const next=(value||'UNIQUE') as InventoryType; setDraft({...draft,inventory_type:next,quantity:next==='UNIQUE'?'1':draft.quantity}); if(next==='UNIQUE') setHasVariants(false) }}/><Select label="Audience" value={draft.audience} data={['WOMEN','MEN','UNISEX','CHILDREN']} onChange={(value) => setDraft({...draft,audience:(value||'WOMEN') as AudienceSegment})}/><TextInput label="Category" required value={draft.category} onChange={(e) => setDraft({...draft,category:e.currentTarget.value})}/><TextInput label="Fabric" value={draft.fabric} onChange={(e) => setDraft({...draft,fabric:e.currentTarget.value})}/><TextInput label="Colour" value={draft.color} onChange={(e) => setDraft({...draft,color:e.currentTarget.value})}/><TextInput label="Selling price" type="number" required value={draft.selling_price} onChange={(e) => setDraft({...draft,selling_price:e.currentTarget.value})}/><TextInput label="Cost price" type="number" value={draft.cost_price} onChange={(e) => setDraft({...draft,cost_price:e.currentTarget.value})}/><TextInput label="Collection" value={draft.collection} onChange={(e) => setDraft({...draft,collection:e.currentTarget.value})}/><TextInput label="Season" value={draft.season} onChange={(e) => setDraft({...draft,season:e.currentTarget.value})}/><Textarea label="Description" value={draft.description} onChange={(e) => setDraft({...draft,description:e.currentTarget.value})}/></SimpleGrid>}
      {step === 1 && <Stack><Text fw={800} size="lg">Product photography</Text><FileButton onChange={(selected) => selected && setFiles((rows) => [...rows,...selected])} accept="image/png,image/jpeg,image/webp" multiple>{(props) => <Button {...props} variant="light" color="grape" leftSection={<ImagePlus size={17}/>}>Add images</Button>}</FileButton><SimpleGrid cols={{base:2,sm:3,md:4}}>{files.map((file,index) => <Paper key={`${file.name}-${index}`} withBorder p="xs"><Image src={URL.createObjectURL(file)} h={150} fit="cover" radius="md"/><Group justify="space-between" mt="xs"><Text size="xs" truncate>{file.name}</Text><ActionIcon color="red" variant="subtle" onClick={() => setFiles((rows) => rows.filter((_,i) => i!==index))}><X size={15}/></ActionIcon></Group>{index===0 && <Badge mt={6} color="grape" variant="light">Primary</Badge>}</Paper>)}</SimpleGrid>{files.length===0 && <Paper withBorder p="xl" className="v3-empty-upload"><Camera size={32}/><Text fw={700}>No image yet</Text><Text size="sm" c="dimmed">You can continue and add one later.</Text></Paper>}</Stack>}
      {step === 2 && <Stack><Group justify="space-between"><Box><Text fw={800} size="lg">Variants & opening stock</Text><Text size="sm" c="dimmed">Variants and their SKUs are optional.</Text></Box><Switch label="This product has variants" checked={hasVariants} disabled={draft.inventory_type==='UNIQUE'} onChange={(e) => setHasVariants(e.currentTarget.checked)}/></Group>{!hasVariants ? <NumberInput label={draft.inventory_type==='YARDAGE'?'Opening metres':'Opening quantity'} min={0} decimalScale={draft.inventory_type==='YARDAGE'?3:0} value={Number(draft.quantity)} onChange={(value) => setDraft({...draft,quantity:String(value||0)})} disabled={draft.inventory_type==='UNIQUE'}/> : <Stack>{variants.map((v,index) => <Paper key={v.key} withBorder p="md"><Group justify="space-between"><Text fw={800}>Variant {index+1}</Text><ActionIcon color="red" variant="subtle" disabled={variants.length===1} onClick={() => setVariants((rows) => rows.filter((row) => row.key!==v.key))}><Trash2 size={15}/></ActionIcon></Group><SimpleGrid cols={{base:1,sm:2,lg:3}} mt="sm"><TextInput label="Variant name" placeholder="Blue / M" required value={v.name} onChange={(e) => patchVariant(v.key,{name:e.currentTarget.value})}/><TextInput label="Size" value={v.size} onChange={(e) => patchVariant(v.key,{size:e.currentTarget.value})}/><TextInput label="Colour" value={v.colour} onChange={(e) => patchVariant(v.key,{colour:e.currentTarget.value})}/><TextInput label="SKU" description="Optional" value={v.sku||''} onChange={(e) => patchVariant(v.key,{sku:e.currentTarget.value})}/><TextInput label="Variant price" type="number" value={v.selling_price||''} onChange={(e) => patchVariant(v.key,{selling_price:e.currentTarget.value})}/><NumberInput label={draft.inventory_type==='YARDAGE'?'Metres':'Stock'} min={0} decimalScale={draft.inventory_type==='YARDAGE'?3:0} value={Number(v.quantity)} onChange={(value) => patchVariant(v.key,{quantity:String(value||0)})}/></SimpleGrid></Paper>)}<Button variant="light" color="grape" leftSection={<Plus size={15}/>} onClick={() => setVariants((rows) => [...rows,variant()])}>Add variant</Button></Stack>}</Stack>}
      {step === 3 && <Stack><Title order={3}>Review</Title><Paper withBorder p="md"><SimpleGrid cols={{base:1,sm:2}}><Box><Text size="xs" c="dimmed">Product</Text><Text fw={800}>{draft.name}</Text></Box><Box><Text size="xs" c="dimmed">Audience</Text><Text fw={800}>{draft.audience}</Text></Box><Box><Text size="xs" c="dimmed">Price</Text><Text fw={800}>{money(draft.selling_price||0)}</Text></Box><Box><Text size="xs" c="dimmed">Images</Text><Text fw={800}>{files.length}</Text></Box><Box><Text size="xs" c="dimmed">SKU</Text><Text fw={800}>{draft.sku||'Not required'}</Text></Box><Box><Text size="xs" c="dimmed">Inventory</Text><Text fw={800}>{hasVariants?`${variants.length} variants`:draft.quantity}</Text></Box></SimpleGrid></Paper></Stack>}
      <Group justify="space-between"><Button variant="subtle" color="gray" leftSection={<ChevronLeft size={16}/>} disabled={step===0||saving} onClick={() => setStep((v) => Math.max(0,v-1))}>Back</Button>{step<3 ? <Button color="grape" rightSection={<ChevronRight size={16}/>} disabled={(step===0&&!basicsOk)||(step===2&&!variantsOk)} onClick={() => setStep((v) => Math.min(3,v+1))}>Continue</Button> : <Button color="grape" loading={saving} leftSection={<PackagePlus size={16}/>} onClick={() => void save()}>Create product</Button>}</Group></Stack>
    </Modal>
  </Stack>
}
