import { useEffect, useMemo, useState } from 'react'
import { ActionIcon, Alert, Badge, Box, Button, Card, Checkbox, Group, Paper, Select, Stack, Text, TextInput, ThemeIcon, Title } from '@mantine/core'
import { ArrowLeft, ArrowRight, Check, Minus, Plus, Search, ShoppingBag, UserRound, X } from 'lucide-react'
import { acceptanceApi, type ProductView, type VariantView } from '../../acceptanceApi'
import { api } from '../../api'
import type { Customer, MeasurementProfile, Order } from '../../types'
import './acceptance-v3.css'

type Sellable = { product: ProductView; variant: VariantView | null }
type CartLine = { sellable: Sellable; quantity: number; requiresTailoring: boolean; measurementProfileId?: number; measurementVersionId?: number }
const steps = ['Customer', 'Items', 'Tailoring', 'Review'] as const
const money = (value: string | number) => `₹${Number(value).toLocaleString('en-IN', { maximumFractionDigits: 2 })}`
const priceOf = (row: Sellable) => Number(row.variant?.selling_price ?? row.product.selling_price)
const availableOf = (row: Sellable) => Number(row.variant?.quantity_available ?? row.product.quantity_available)
const keyOf = (row: Sellable) => `${row.product.id}:${row.variant?.id ?? 'base'}`

function CustomerSearch({ customers, value, onPick }: { customers: Customer[]; value: Customer | null; onPick: (value: Customer | null) => void }) {
  const [query, setQuery] = useState(value ? `${value.name} · ${value.phone}` : '')
  const [open, setOpen] = useState(false)
  const results = useMemo(() => { const needle=query.trim().toLowerCase(); return (needle ? customers.filter((c) => `${c.name} ${c.phone} ${c.email ?? ''}`.toLowerCase().includes(needle)) : customers).slice(0,8) }, [customers,query])
  return <Box className="v3-smart-search"><TextInput size="md" label="Customer" required leftSection={<Search size={16}/>} placeholder="Type name, mobile or email..." value={query} onFocus={() => setOpen(true)} onChange={(e) => { setQuery(e.currentTarget.value); setOpen(true); if(value) onPick(null) }}/>{open && <Box className="v3-search-results">{results.map((c) => <button type="button" key={c.id} onMouseDown={(e) => e.preventDefault()} onClick={() => { onPick(c); setQuery(`${c.name} · ${c.phone}`); setOpen(false) }}><Box><Text fw={800}>{c.name}</Text><Text size="xs" c="dimmed">{c.phone}{c.email?` · ${c.email}`:''}</Text></Box><UserRound size={17}/></button>)}{results.length===0 && <Text size="sm" c="dimmed" p="sm">No matching customer</Text>}</Box>}</Box>
}

function ProductSearch({ products, onPick }: { products: ProductView[]; onPick: (value: Sellable) => void }) {
  const [query,setQuery]=useState(''); const [open,setOpen]=useState(false)
  const sellables = useMemo<Sellable[]>(() => products.flatMap<Sellable>((product) => product.variants.length ? product.variants.map((variant): Sellable => ({product,variant})) : [{product,variant:null}]), [products])
  const results = useMemo(() => { const needle=query.trim().toLowerCase(); return sellables.filter((row) => { if(availableOf(row)<=0) return false; const text=`${row.product.name} ${row.product.sku??''} ${row.product.category} ${row.product.fabric??''} ${row.product.color??''} ${row.variant?.name??''} ${row.variant?.sku??''} ${Object.values(row.variant?.option_values??{}).join(' ')}`.toLowerCase(); return !needle || text.includes(needle) }).slice(0,10) }, [query,sellables])
  return <Box className="v3-smart-search"><TextInput size="md" label="Add product" leftSection={<Search size={16}/>} placeholder="Search product, variant, SKU, fabric or colour..." value={query} onFocus={() => setOpen(true)} onChange={(e) => {setQuery(e.currentTarget.value);setOpen(true)}}/>{open && <Box className="v3-search-results">{results.map((row) => <button type="button" key={keyOf(row)} onMouseDown={(e)=>e.preventDefault()} onClick={() => {onPick(row);setQuery('');setOpen(false)}}><Box><Text fw={800}>{row.product.name}{row.variant?` · ${row.variant.name}`:''}</Text><Text size="xs" c="dimmed">{row.variant?.sku||row.product.sku||'No SKU'} · {row.product.category} · {availableOf(row)} {row.product.inventory_type==='YARDAGE'?'m':'available'}</Text></Box><Text fw={800}>{money(priceOf(row))}</Text></button>)}{results.length===0 && <Text size="sm" c="dimmed" p="sm">No matching sellable product</Text>}</Box>}</Box>
}

export function GuidedOrdersWorkspaceV4({ customers, orders, onCreated }: { customers: Customer[]; orders: Order[]; onCreated: () => void }) {
  const [products,setProducts]=useState<ProductView[]>([]); const [step,setStep]=useState(0); const [customer,setCustomer]=useState<Customer|null>(null); const [cart,setCart]=useState<CartLine[]>([]); const [profiles,setProfiles]=useState<MeasurementProfile[]>([]); const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [submitting,setSubmitting]=useState(false)
  useEffect(() => { void acceptanceApi.products().then(setProducts).catch(() => setError('Unable to load products.')) }, [])
  useEffect(() => { if(!customer) return; let active=true; void api.customerMeasurementProfiles(customer.id).then((rows)=>{if(active)setProfiles(rows)}).catch(()=>{if(active)setProfiles([])}); return()=>{active=false} }, [customer])
  const total=cart.reduce((sum,line)=>sum+priceOf(line.sellable)*line.quantity,0); const recentOrders=customer?orders.filter((o)=>o.customer_id===customer.id).slice(0,3):[]
  function add(row: Sellable){setCart((rows)=>{const key=keyOf(row);const existing=rows.find((line)=>keyOf(line.sellable)===key);if(existing)return rows.map((line)=>keyOf(line.sellable)===key?{...line,quantity:line.sellable.product.inventory_type==='UNIQUE'?1:Math.min(line.quantity+1,availableOf(line.sellable))}:line);return[...rows,{sellable:row,quantity:1,requiresTailoring:false}]})}
  function measurement(key:string,profileId:string|null){const profile=profiles.find((p)=>p.id===Number(profileId));setCart((rows)=>rows.map((line)=>keyOf(line.sellable)===key?{...line,measurementProfileId:profile?.id,measurementVersionId:profile?.latest_version?.id}:line))}
  const canContinue=step===0?Boolean(customer):step===1?cart.length>0:true
  async function submit(){if(!customer||!cart.length)return;setSubmitting(true);setError('');setSuccess('');try{const created=await acceptanceApi.createVariantAwareOrder({customer_id:customer.id,lines:cart.map((line)=>({item_id:line.sellable.product.id,variant_id:line.sellable.variant?.id,quantity:String(line.quantity),requires_tailoring:line.requiresTailoring,measurement_profile_id:line.measurementProfileId,measurement_version_id:line.measurementVersionId}))});setSuccess(`Order #${created.id} created.`);setCart([]);setCustomer(null);setProfiles([]);setStep(0);onCreated();setProducts(await acceptanceApi.products())}catch(e){setError(e instanceof Error?e.message:'Unable to create order.')}finally{setSubmitting(false)}}
  return <Stack gap="lg"><Group justify="space-between" align="flex-end" className="v3-page-heading"><Box><Text size="sm" c="dimmed">Operations</Text><Title order={1}>Orders</Title><Text c="dimmed">Search the customer and the exact sellable variant.</Text></Box><Badge color="grape" variant="light" size="lg">{cart.length} lines · {money(total)}</Badge></Group>{error&&<Alert color="red">{error}</Alert>}{success&&<Alert color="teal">{success}</Alert>}
    <Paper withBorder p="sm" className="v3-wizard-progress"><Group gap="xs" wrap="nowrap">{steps.map((label,index)=><Box key={label} className={index===step?'active':index<step?'done':''} onClick={()=>index<step&&setStep(index)}><ThemeIcon size={30} radius="xl" color="grape" variant={index<=step?'filled':'light'}>{index<step?<Check size={14}/>:<Text size="xs" fw={900}>{index+1}</Text>}</ThemeIcon><Text size="sm" fw={index===step?800:600} visibleFrom="sm">{label}</Text></Box>)}</Group></Paper>
    {step===0&&<Paper withBorder p="lg"><Stack><Text fw={800} size="lg">Who is this order for?</Text><CustomerSearch customers={customers} value={customer} onPick={(value)=>{setCustomer(value);if(!value)setProfiles([])}}/>{customer&&<Card withBorder><Group justify="space-between"><Box><Text fw={900}>{customer.name}</Text><Text size="sm" c="dimmed">{customer.phone}</Text></Box><Badge color="grape" variant="light">{recentOrders.length} recent orders</Badge></Group></Card>}</Stack></Paper>}
    {step===1&&<Paper withBorder p="lg"><Stack><Text fw={800} size="lg">What are they buying?</Text><ProductSearch products={products} onPick={add}/>{cart.length===0&&<Box className="v3-empty-cart"><ShoppingBag size={28}/><Text fw={700}>No items yet</Text></Box>}{cart.map((line)=>{const key=keyOf(line.sellable);const max=Math.max(1,availableOf(line.sellable));return<Card key={key} withBorder><Group justify="space-between"><Box><Text fw={800}>{line.sellable.product.name}{line.sellable.variant?` · ${line.sellable.variant.name}`:''}</Text><Text size="sm" c="dimmed">{line.sellable.variant?.sku||line.sellable.product.sku||'No SKU'}</Text></Box><Group><Group gap={0}><ActionIcon variant="default" disabled={line.sellable.product.inventory_type==='UNIQUE'} onClick={()=>setCart((rows)=>rows.map((r)=>keyOf(r.sellable)===key?{...r,quantity:Math.max(1,r.quantity-1)}:r))}><Minus size={14}/></ActionIcon><Text w={40} ta="center" fw={800}>{line.quantity}</Text><ActionIcon variant="default" disabled={line.sellable.product.inventory_type==='UNIQUE'||line.quantity>=max} onClick={()=>setCart((rows)=>rows.map((r)=>keyOf(r.sellable)===key?{...r,quantity:Math.min(max,r.quantity+1)}:r))}><Plus size={14}/></ActionIcon></Group><Text fw={900}>{money(priceOf(line.sellable)*line.quantity)}</Text><ActionIcon color="red" variant="subtle" onClick={()=>setCart((rows)=>rows.filter((r)=>keyOf(r.sellable)!==key))}><X size={15}/></ActionIcon></Group></Group></Card>})}</Stack></Paper>}
    {step===2&&<Paper withBorder p="lg"><Stack><Text fw={800} size="lg">Tailoring & measurements</Text>{cart.map((line)=>{const key=keyOf(line.sellable);return<Card key={key} withBorder><Stack><Group justify="space-between"><Box><Text fw={800}>{line.sellable.product.name}{line.sellable.variant?` · ${line.sellable.variant.name}`:''}</Text><Text size="sm" c="dimmed">{line.sellable.product.category}</Text></Box><Checkbox label="Requires tailoring" checked={line.requiresTailoring} onChange={(e)=>setCart((rows)=>rows.map((r)=>keyOf(r.sellable)===key?{...r,requiresTailoring:e.currentTarget.checked,measurementProfileId:e.currentTarget.checked?r.measurementProfileId:undefined,measurementVersionId:e.currentTarget.checked?r.measurementVersionId:undefined}:r))}/></Group>{line.requiresTailoring&&(profiles.length?<Select label="Measurement profile" clearable placeholder="Use saved measurements" value={line.measurementProfileId?.toString()??null} onChange={(value)=>measurement(key,value)} data={profiles.map((p)=>({value:String(p.id),label:`${p.name}${p.garment_type?` · ${p.garment_type}`:''}${p.latest_version?` · v${p.latest_version.version_number}`:''}`}))}/>:<Alert color="grape" variant="light">No saved measurement profile yet.</Alert>)}</Stack></Card>})}</Stack></Paper>}
    {step===3&&<Paper withBorder p="lg"><Stack><Text fw={800} size="lg">Review and confirm</Text><Card withBorder><Text size="xs" c="dimmed">CUSTOMER</Text><Text fw={900}>{customer?.name}</Text></Card>{cart.map((line)=><Card key={keyOf(line.sellable)} withBorder><Group justify="space-between"><Box><Text fw={800}>{line.sellable.product.name}{line.sellable.variant?` · ${line.sellable.variant.name}`:''}</Text><Text size="sm" c="dimmed">Qty {line.quantity}{line.requiresTailoring?' · Tailoring':''}{line.measurementProfileId?' · Measurements linked':''}</Text></Box><Text fw={900}>{money(priceOf(line.sellable)*line.quantity)}</Text></Group></Card>)}<Box className="v3-review-total"><Text size="sm" c="dimmed">Order total</Text><Title order={2}>{money(total)}</Title></Box><Button color="grape" size="md" loading={submitting} leftSection={<Check size={17}/>} onClick={()=>void submit()}>Confirm order</Button></Stack></Paper>}
    <Group justify="space-between"><Button variant="subtle" color="gray" leftSection={<ArrowLeft size={16}/>} disabled={step===0} onClick={()=>setStep((v)=>Math.max(0,v-1))}>Back</Button>{step<3&&<Button color="grape" rightSection={<ArrowRight size={16}/>} disabled={!canContinue} onClick={()=>setStep((v)=>Math.min(3,v+1))}>Continue</Button>}</Group>
  </Stack>
}
